### ISSUE TITLE
OPPO(realme)系统推送不成功 hmspush概率黑屏

### ISSUE THREAD

**Issue by n0raml** [fei-ke/HMSPush#9]
1，官方教程 -》推送不成功，libchecker查看广播被划线。应用通知无其他，酷安机型为显示更改
2，使用机型伪装模块 -》推送不成功，libchecker查看广播被划线。应用通知无其他
3，使用老版本magisk模块-》 推送不成功，libchecker查看广播被划线。应用通知无其他

未黑屏log
[LSPosed_2022-08-18T09_09_40.451.zip](https://github.com/fei-ke/HMSPush/files/9366981/LSPosed_2022-08-18T09_09_40.451.zip)

黑屏log
[LSPosed_2022-08-18T09_33_04.813.zip](https://github.com/fei-ke/HMSPush/files/9366982/LSPosed_2022-08-18T09_33_04.813.zip)

**Comment by fei-ke** [comment]
HMS Core 给自启权限，不要用其他工具对其进行阻止或禁用，日志显示HMS Core一直在重复启动，重复崩溃
```
Crash unexpectedly: java.lang.RuntimeException: Unable to get provider com.huawei.hms.commonkit.config.CommonKitProvider: java.lang.ClassNotFoundException: Didn't find class "com.huawei.hms.commonkit.config.CommonKitProvider" on path: DexPathList[[zip file "/data/app/~~LCA-faZDvAHNiqXP5WuF9Q==/com.huawei.hwid-jDdEDNGXSqIkMprQ6McgkA==/base.apk"],nativeLibraryDirectories=[/data/app/~~LCA-faZDvAHNiqXP5WuF9Q==/com.huawei.hwid-jDdEDNGXSqIkMprQ6McgkA==/lib/arm64, /data/app/~~LCA-faZDvAHNiqXP5WuF9Q==/com.huawei.hwid-jDdEDNGXSqIkMprQ6McgkA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64, /vendor/lib64, /odm/lib64]]
	at android.app.ActivityThread.installProvider(ActivityThread.java:7816)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7352)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7238)
	at android.app.ActivityThread.access$1500(ActivityThread.java:302)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2144)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:260)
	at android.app.ActivityThread.main(ActivityThread.java:8258)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.huawei.hms.commonkit.config.CommonKitProvider" on path: DexPathList[[zip file "/data/app/~~LCA-faZDvAHNiqXP5WuF9Q==/com.huawei.hwid-jDdEDNGXSqIkMprQ6McgkA==/base.apk"],nativeLibraryDirectories=[/data/app/~~LCA-faZDvAHNiqXP5WuF9Q==/com.huawei.hwid-jDdEDNGXSqIkMprQ6McgkA==/lib/arm64, /data/app/~~LCA-faZDvAHNiqXP5WuF9Q==/com.huawei.hwid-jDdEDNGXSqIkMprQ6McgkA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64, /vendor/lib64, /odm/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
	at androidx.core.app.CoreComponentFactory.instantiateProvider(SourceFile:1)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7800)
	... 10 more
```

**Comment by n0raml** [comment]
但是不破溃 也无法推送，有系统默认通道

**Comment by n0raml** [comment]
> HMS Core 给予自启权限，不要显示一直在进行禁止或禁止使用其他日志工具，HMS Core 一直在重复启动，重复退出
> 
> ```
> Crash unexpectedly: java.lang.RuntimeException: Unable to get provider com.huawei.hms.commonkit.config.CommonKitProvider: java.lang.ClassNotFoundException: Didn't find class "com.huawei.hms.commonkit.config.CommonKitProvider" on path: DexPathList[[zip file "/data/app/~~LCA-faZDvAHNiqXP5WuF9Q==/com.huawei.hwid-jDdEDNGXSqIkMprQ6McgkA==/base.apk"],nativeLibraryDirectories=[/data/app/~~LCA-faZDvAHNiqXP5WuF9Q==/com.huawei.hwid-jDdEDNGXSqIkMprQ6McgkA==/lib/arm64, /data/app/~~LCA-faZDvAHNiqXP5WuF9Q==/com.huawei.hwid-jDdEDNGXSqIkMprQ6McgkA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64, /vendor/lib64, /odm/lib64]]
> 	at android.app.ActivityThread.installProvider(ActivityThread.java:7816)
> 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7352)
> 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7238)
> 	at android.app.ActivityThread.access$1500(ActivityThread.java:302)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2144)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loop(Looper.java:260)
> 	at android.app.ActivityThread.main(ActivityThread.java:8258)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
> Caused by: java.lang.ClassNotFoundException: Didn't find class "com.huawei.hms.commonkit.config.CommonKitProvider" on path: DexPathList[[zip file "/data/app/~~LCA-faZDvAHNiqXP5WuF9Q==/com.huawei.hwid-jDdEDNGXSqIkMprQ6McgkA==/base.apk"],nativeLibraryDirectories=[/data/app/~~LCA-faZDvAHNiqXP5WuF9Q==/com.huawei.hwid-jDdEDNGXSqIkMprQ6McgkA==/lib/arm64, /data/app/~~LCA-faZDvAHNiqXP5WuF9Q==/com.huawei.hwid-jDdEDNGXSqIkMprQ6McgkA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64, /vendor/lib64, /odm/lib64]]
> 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
> 	at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
> 	at androidx.core.app.CoreComponentFactory.instantiateProvider(SourceFile:1)
> 	at android.app.ActivityThread.installProvider(ActivityThread.java:7800)
> 	... 10 more
> ```
经过各种方法，在realme宣告失败

**Comment by n0raml** [comment]
强制打开广播后再打开应用，还是不行，
[LSPosed_2022-08-18T12_00_53.776.zip](https://github.com/fei-ke/HMSPush/files/9367548/LSPosed_2022-08-18T12_00_53.776.zip)

**Comment by fei-ke** [comment]
@n0raml https://github.com/fei-ke/HMSPush/actions/runs/2881537158 下这个包试试试，传一下日志

**Comment by n0raml** [comment]
> @n0raml https://github.com/fei-ke/HMSPush/actions/runs/2881537158 下这个包试试试，传一下日志

无多出的分类。也不能通
[LSPosed_2022-08-19T10_53_32.810.zip](https://github.com/fei-ke/HMSPush/files/9378856/LSPosed_2022-08-19T10_53_32.810.zip)
知

**Comment by n0raml** [comment]
> @n0raml https://github.com/fei-ke/HMSPush/actions/runs/2881537158 下这个包试试试，传一下日志

----part 3 start----
[ 2022-08-19T12:09:19.017    10239: 14917: 15477 I/LSPosed-Bridge  ] [HMSPush]  NotificationManagerEx  use SystemNotificationManager
[ 2022-08-19T12:09:19.021    10239: 14917: 15477 I/LSPosed-Bridge  ] [HMSPush]  NotificationManagerEx  areNotificationsEnabled() called with: packageName = com.tencent.tim, userId = 0
[ 2022-08-19T12:09:19.024    10239: 14917: 15477 I/LSPosed-Bridge  ] [HMSPush]  NotificationManagerEx  tryInvoke: 
[ 2022-08-19T12:09:19.024    10239: 14917: 15477 E/LSPosed-Bridge  ] de.robv.android.xposed.XposedHelpers$InvocationTargetError: java.lang.SecurityException: Caller not system or systemui or same package: uid 10239 does not have android.permission.STATUS_BAR_SERVICE.
	at de.robv.android.xposed.XposedHelpers.callMethod(Unknown Source:20)
	at s.d0.c(Unknown Source:10)
	at a.c.e(:1)
	at com.huawei.android.app.NotificationManagerEx.areNotificationsEnabled(:2)
	at z.t.f(:1)
	at z.p0.beforeHookedMethod(:2)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.areNotificationsEnabled(Unknown Source:18)
	at bo.s(Unknown Source:46)
	at fp.a(Unknown Source:22)
	at kp.process(Unknown Source:110)
	at ip.a(Unknown Source:56)
	at Do.a(Unknown Source:112)
	at Do.a(Unknown Source:6)
	at mo.g(Unknown Source:58)
	at io$a.onReceive(Unknown Source:30)
	at io$a.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:260)
	at io.run(Unknown Source:22)
Caused by: java.lang.SecurityException: Caller not system or systemui or same package: uid 10239 does not have android.permission.STATUS_BAR_SERVICE.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2389)
	at android.os.Parcel.createException(Parcel.java:2373)
	at android.os.Parcel.readException(Parcel.java:2356)
	at android.os.Parcel.readException(Parcel.java:2298)
	at android.app.INotificationManager$Stub$Proxy.areNotificationsEnabledForPackage(INotificationManager.java:3387)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.XposedHelpers.callMethod(Unknown Source:8)
	... 20 more
Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.ContextImpl.enforce(ContextImpl.java:2089)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:110)
	at LSPHooker_.enforce(Unknown Source:35)

[ 2022-08-19T12:09:19.024    10239: 14917: 15477 I/LSPosed-Bridge  ] [HMSPush]  NotificationManagerEx  tryInvoke targetException: 
[ 2022-08-19T12:09:19.024    10239: 14917: 15477 E/LSPosed-Bridge  ] java.lang.SecurityException: Caller not system or systemui or same package: uid 10239 does not have android.permission.STATUS_BAR_SERVICE.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2389)
	at android.os.Parcel.createException(Parcel.java:2373)
	at android.os.Parcel.readException(Parcel.java:2356)
	at android.os.Parcel.readException(Parcel.java:2298)
	at android.app.INotificationManager$Stub$Proxy.areNotificationsEnabledForPackage(INotificationManager.java:3387)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.XposedHelpers.callMethod(Unknown Source:8)
	at s.d0.c(Unknown Source:10)
	at a.c.e(:1)
	at com.huawei.android.app.NotificationManagerEx.areNotificationsEnabled(:2)
	at z.t.f(:1)
	at z.p0.beforeHookedMethod(:2)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.areNotificationsEnabled(Unknown Source:18)
	at bo.s(Unknown Source:46)
	at fp.a(Unknown Source:22)
	at kp.process(Unknown Source:110)
	at ip.a(Unknown Source:56)
	at Do.a(Unknown Source:112)
	at Do.a(Unknown Source:6)
	at mo.g(Unknown Source:58)
	at io$a.onReceive(Unknown Source:30)
	at io$a.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:260)
	at io.run(Unknown Source:22)
Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.ContextImpl.enforce(ContextImpl.java:2089)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:110)
	at LSPHooker_.enforce(Unknown Source:35)

[ 2022-08-19T12:09:32.469    10239: 14917: 15477 I/LSPosed-Bridge  ] [HMSPush]  NotificationManagerEx  areNotificationsEnabled() called with: packageName = com.tencent.tim, userId = 0
[ 2022-08-19T12:09:32.470    10239: 14917: 15477 I/LSPosed-Bridge  ] [HMSPush]  NotificationManagerEx  tryInvoke: 
[ 2022-08-19T12:09:32.470    10239: 14917: 15477 E/LSPosed-Bridge  ] de.robv.android.xposed.XposedHelpers$InvocationTargetError: java.lang.SecurityException: Caller not system or systemui or same package: uid 10239 does not have android.permission.STATUS_BAR_SERVICE.
	at de.robv.android.xposed.XposedHelpers.callMethod(Unknown Source:20)
	at s.d0.c(Unknown Source:10)
	at a.c.e(:1)
	at com.huawei.android.app.NotificationManagerEx.areNotificationsEnabled(:2)
	at z.t.f(:1)
	at z.p0.beforeHookedMethod(:2)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.areNotificationsEnabled(Unknown Source:18)
	at bo.s(Unknown Source:46)
	at fp.a(Unknown Source:22)
	at kp.process(Unknown Source:110)
	at ip.a(Unknown Source:56)
	at Do.a(Unknown Source:112)
	at Do.a(Unknown Source:6)
	at mo.g(Unknown Source:58)
	at io$a.onReceive(Unknown Source:30)
	at io$a.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:260)
	at io.run(Unknown Source:22)
Caused by: java.lang.SecurityException: Caller not system or systemui or same package: uid 10239 does not have android.permission.STATUS_BAR_SERVICE.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2389)
	at android.os.Parcel.createException(Parcel.java:2373)
	at android.os.Parcel.readException(Parcel.java:2356)
	at android.os.Parcel.readException(Parcel.java:2298)
	at android.app.INotificationManager$Stub$Proxy.areNotificationsEnabledForPackage(INotificationManager.java:3387)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.XposedHelpers.callMethod(Unknown Source:8)
	... 20 more
Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.ContextImpl.enforce(ContextImpl.java:2089)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:110)
	at LSPHooker_.enforce(Unknown Source:35)

[ 2022-08-19T12:09:32.471    10239: 14917: 15477 I/LSPosed-Bridge  ] [HMSPush]  NotificationManagerEx  tryInvoke targetException: 
[ 2022-08-19T12:09:32.471    10239: 14917: 15477 E/LSPosed-Bridge  ] java.lang.SecurityException: Caller not system or systemui or same package: uid 10239 does not have android.permission.STATUS_BAR_SERVICE.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2389)
	at android.os.Parcel.createException(Parcel.java:2373)
	at android.os.Parcel.readException(Parcel.java:2356)
	at android.os.Parcel.readException(Parcel.java:2298)
	at android.app.INotificationManager$Stub$Proxy.areNotificationsEnabledForPackage(INotificationManager.java:3387)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.XposedHelpers.callMethod(Unknown Source:8)
	at s.d0.c(Unknown Source:10)
	at a.c.e(:1)
	at com.huawei.android.app.NotificationManagerEx.areNotificationsEnabled(:2)
	at z.t.f(:1)
	at z.p0.beforeHookedMethod(:2)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.areNotificationsEnabled(Unknown Source:18)
	at bo.s(Unknown Source:46)
	at fp.a(Unknown Source:22)
	at kp.process(Unknown Source:110)
	at ip.a(Unknown Source:56)
	at Do.a(Unknown Source:112)
	at Do.a(Unknown Source:6)
	at mo.g(Unknown Source:58)
	at io$a.onReceive(Unknown Source:30)
	at io$a.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:260)
	at io.run(Unknown Source:22)
Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.ContextImpl.enforce(ContextImpl.java:2089)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:110)
	at LSPHooker_.enforce(Unknown Source:35)

[ 2022-08-19T12:10:16.885    10239: 14917: 15477 I/LSPosed-Bridge  ] [HMSPush]  NotificationManagerEx  areNotificationsEnabled() called with: packageName = com.tencent.tim, userId = 0
[ 2022-08-19T12:10:16.886    10239: 14917: 15477 I/LSPosed-Bridge  ] [HMSPush]  NotificationManagerEx  tryInvoke: 
[ 2022-08-19T12:10:16.886    10239: 14917: 15477 E/LSPosed-Bridge  ] de.robv.android.xposed.XposedHelpers$InvocationTargetError: java.lang.SecurityException: Caller not system or systemui or same package: uid 10239 does not have android.permission.STATUS_BAR_SERVICE.
	at de.robv.android.xposed.XposedHelpers.callMethod(Unknown Source:20)
	at s.d0.c(Unknown Source:10)
	at a.c.e(:1)
	at com.huawei.android.app.NotificationManagerEx.areNotificationsEnabled(:2)
	at z.t.f(:1)
	at z.p0.beforeHookedMethod(:2)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.areNotificationsEnabled(Unknown Source:18)
	at bo.s(Unknown Source:46)
	at fp.a(Unknown Source:22)
	at kp.process(Unknown Source:110)
	at ip.a(Unknown Source:56)
	at Do.a(Unknown Source:112)
	at Do.a(Unknown Source:6)
	at mo.g(Unknown Source:58)
	at io$a.onReceive(Unknown Source:30)
	at io$a.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:260)
	at io.run(Unknown Source:22)
Caused by: java.lang.SecurityException: Caller not system or systemui or same package: uid 10239 does not have android.permission.STATUS_BAR_SERVICE.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2389)
	at android.os.Parcel.createException(Parcel.java:2373)
	at android.os.Parcel.readException(Parcel.java:2356)
	at android.os.Parcel.readException(Parcel.java:2298)
	at android.app.INotificationManager$Stub$Proxy.areNotificationsEnabledForPackage(INotificationManager.java:3387)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.XposedHelpers.callMethod(Unknown Source:8)
	... 20 more
Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.ContextImpl.enforce(ContextImpl.java:2089)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:110)
	at LSPHooker_.enforce(Unknown Source:35)

[ 2022-08-19T12:10:16.887    10239: 14917: 15477 I/LSPosed-Bridge  ] [HMSPush]  NotificationManagerEx  tryInvoke targetException: 
[ 2022-08-19T12:10:16.887    10239: 14917: 15477 E/LSPosed-Bridge  ] java.lang.SecurityException: Caller not system or systemui or same package: uid 10239 does not have android.permission.STATUS_BAR_SERVICE.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2389)
	at android.os.Parcel.createException(Parcel.java:2373)
	at android.os.Parcel.readException(Parcel.java:2356)
	at android.os.Parcel.readException(Parcel.java:2298)
	at android.app.INotificationManager$Stub$Proxy.areNotificationsEnabledForPackage(INotificationManager.java:3387)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.XposedHelpers.callMethod(Unknown Source:8)
	at s.d0.c(Unknown Source:10)
	at a.c.e(:1)
	at com.huawei.android.app.NotificationManagerEx.areNotificationsEnabled(:2)
	at z.t.f(:1)
	at z.p0.beforeHookedMethod(:2)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.areNotificationsEnabled(Unknown Source:18)
	at bo.s(Unknown Source:46)
	at fp.a(Unknown Source:22)
	at kp.process(Unknown Source:110)
	at ip.a(Unknown Source:56)
	at Do.a(Unknown Source:112)
	at Do.a(Unknown Source:6)
	at mo.g(Unknown Source:58)
	at io$a.onReceive(Unknown Source:30)
	at io$a.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:260)
	at io.run(Unknown Source:22)
Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.ContextImpl.enforce(ContextImpl.java:2089)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:110)
	at LSPHooker_.enforce(Unknown Source:35)

[ 2022-08-19T12:10:27.835    10239: 14917: 15477 I/LSPosed-Bridge  ] [HMSPush]  NotificationManagerEx  areNotificationsEnabled() called with: packageName = com.tencent.tim, userId = 0
[ 2022-08-19T12:10:27.836    10239: 14917: 15477 I/LSPosed-Bridge  ] [HMSPush]  NotificationManagerEx  tryInvoke: 
[ 2022-08-19T12:10:27.836    10239: 14917: 15477 E/LSPosed-Bridge  ] de.robv.android.xposed.XposedHelpers$InvocationTargetError: java.lang.SecurityException: Caller not system or systemui or same package: uid 10239 does not have android.permission.STATUS_BAR_SERVICE.
	at de.robv.android.xposed.XposedHelpers.callMethod(Unknown Source:20)
	at s.d0.c(Unknown Source:10)
	at a.c.e(:1)
	at com.huawei.android.app.NotificationManagerEx.areNotificationsEnabled(:2)
	at z.t.f(:1)
	at z.p0.beforeHookedMethod(:2)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.areNotificationsEnabled(Unknown Source:18)
	at bo.s(Unknown Source:46)
	at fp.a(Unknown Source:22)
	at kp.process(Unknown Source:110)
	at ip.a(Unknown Source:56)
	at Do.a(Unknown Source:112)
	at Do.a(Unknown Source:6)
	at mo.g(Unknown Source:58)
	at io$a.onReceive(Unknown Source:30)
	at io$a.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:260)
	at io.run(Unknown Source:22)
Caused by: java.lang.SecurityException: Caller not system or systemui or same package: uid 10239 does not have android.permission.STATUS_BAR_SERVICE.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2389)
	at android.os.Parcel.createException(Parcel.java:2373)
	at android.os.Parcel.readException(Parcel.java:2356)
	at android.os.Parcel.readException(Parcel.java:2298)
	at android.app.INotificationManager$Stub$Proxy.areNotificationsEnabledForPackage(INotificationManager.java:3387)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.XposedHelpers.callMethod(Unknown Source:8)
	... 20 more
Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.ContextImpl.enforce(ContextImpl.java:2089)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:110)
	at LSPHooker_.enforce(Unknown Source:35)

[ 2022-08-19T12:10:27.836    10239: 14917: 15477 I/LSPosed-Bridge  ] [HMSPush]  NotificationManagerEx  tryInvoke targetException: 
[ 2022-08-19T12:10:27.837    10239: 14917: 15477 E/LSPosed-Bridge  ] java.lang.SecurityException: Caller not system or systemui or same package: uid 10239 does not have android.permission.STATUS_BAR_SERVICE.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2389)
	at android.os.Parcel.createException(Parcel.java:2373)
	at android.os.Parcel.readException(Parcel.java:2356)
	at android.os.Parcel.readException(Parcel.java:2298)
	at android.app.INotificationManager$Stub$Proxy.areNotificationsEnabledForPackage(INotificationManager.java:3387)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.XposedHelpers.callMethod(Unknown Source:8)
	at s.d0.c(Unknown Source:10)
	at a.c.e(:1)
	at com.huawei.android.app.NotificationManagerEx.areNotificationsEnabled(:2)
	at z.t.f(:1)
	at z.p0.beforeHookedMethod(:2)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.areNotificationsEnabled(Unknown Source:18)
	at bo.s(Unknown Source:46)
	at fp.a(Unknown Source:22)
	at kp.process(Unknown Source:110)
	at ip.a(Unknown Source:56)
	at Do.a(Unknown Source:112)
	at Do.a(Unknown Source:6)
	at mo.g(Unknown Source:58)
	at io$a.onReceive(Unknown Source:30)
	at io$a.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:260)
	at io.run(Unknown Source:22)
Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.ContextImpl.enforce(ContextImpl.java:2089)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:110)
	at LSPHooker_.enforce(Unknown Source:35)

**Comment by n0raml** [comment]
> @n0raml https://github.com/fei-ke/HMSPush/actions/runs/2881537158 下这个包试试试，传一下日志
[modules_2022-08-19T12_09_18.201.log](https://github.com/fei-ke/HMSPush/files/9379137/modules_2022-08-19T12_09_18.201.log)
